# Cloudflare Pages/Workers Configuration for ScoutGUI

name = "scoutgui"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# Pages configuration
pages_build_output_dir = ".vercel/output/static"

# OAuth Routing (Consistent Across All Servers)
#
# OAuth Callbacks (special direct route):
#   Pattern: /v1/auth/oauth/{agent_id}/{provider}/callback
#   Example: https://scoutapi.ciris.ai/v1/auth/oauth/scout-remote-test-dahrb9/google/callback
#
# OAuth Login & All Other API Calls (via standard API route):
#   Pattern: /api/{agent_id}/v1/...
#   Example: https://scoutapi.ciris.ai/api/scout-remote-test-dahrb9/v1/auth/oauth/google/login

# Environment variables
[vars]
NEXT_PUBLIC_API_BASE_URL = "https://scoutapi.ciris.ai/api/scout-remote-test-dahrb9/v1"
NEXT_PUBLIC_SCOUT_API_URL = "https://scoutapi.ciris.ai/api/scout-remote-test-dahrb9/v1"

# Environment variables (for production)
[env.production]
vars = { }

# You can set secrets using: wrangler secret put <KEY>
# For example: wrangler secret put NEXT_PUBLIC_SCOUT_API_URL

# KV Namespaces (if needed for caching)
# [[kv_namespaces]]
# binding = "CACHE"
# id = "your-kv-namespace-id"

# Routes configuration (optional)
# routes = [
#   { pattern = "scout.ciris.ai", zone_name = "ciris.ai" }
# ]
