# Cloudflare Pages/Workers Configuration for ScoutGUI

name = "scoutgui"
compatibility_date = "2024-01-01"

# Pages configuration
pages_build_output_dir = ".vercel/output/static"

# Environment variables (for production)
[env.production]
vars = { }

# You can set secrets using: wrangler secret put <KEY>
# For example: wrangler secret put NEXT_PUBLIC_SCOUT_API_URL

# KV Namespaces (if needed for caching)
# [[kv_namespaces]]
# binding = "CACHE"
# id = "your-kv-namespace-id"

# Routes configuration (optional)
# routes = [
#   { pattern = "scout.ciris.ai", zone_name = "ciris.ai" }
# ]
