version: "3.9"
services:
  ciris-api:
    build:
      context: ../..
      dockerfile: CIRISGUI/docker/Dockerfile.ciris
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    ports:
      - "8080:8080"
  agui:
    build:
      context: ../..
      dockerfile: CIRISGUI/docker/Dockerfile.agui
    environment:
      NEXT_PUBLIC_CIRIS_API_URL: http://localhost:8080
    ports:
      - "3000:3000"
    depends_on:
      - ciris-api
