version: "3.9"
services:
  agui:
    build:
      context: ../..
      dockerfile: CIRISGUI/docker/Dockerfile.agui
    environment:
      NEXT_PUBLIC_CIRIS_API_URL: http://host.docker.internal:8080
    ports:
      - "3000:3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
